apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: web-function
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/thomasvitale/devoxxuk/web-function:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
            periodSeconds: 10
          resources:
            requests:
              memory: 512Mi
              cpu: "0.1"
            limits:
              memory: 512Mi
              cpu: "2"
